// pipeline {
//     agent {
// 	docker {
// 	    image 'maven:3.9.2'
// 	    args '-v /root/.m2:/root/.m2'
// 	}
// }
//     stages {
//         stage('Build') { 
//             steps {
//                 sh 'mvn -B -DskipTests clean package' 
//             }
//         }
//     }
// }
pipeline {
    agent any
     tools {
        maven 'Maven_3'
    }
    
    stages {

        stage('Verify Maven Version') {
            steps {
                script {
                    sh 'mvn -v'  // This will print the Maven version
                }
            }
        }
        
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
