pipeline {
    agent {
	dockerContainer {
	    image 'maven:3.9.9'
	    args '-v /root/.m2:/root/.m2'
	}
}
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
